alias pa="php artisan"
alias clean='pa config:clear && pa cache:clear && pa route:clear && pa view:clear'
alias mainwh="cd /var/www/html/mainwh"
alias tms="cd /var/www/html/TMS"
alias dd="cd /var/www/html/dd"
alias hrms="cd /var/www/html/digital201"
alias phpv="update-alternatives --config php"
alias php81="update-alternatives --set php /usr/bin/php8.1"
alias php80="update-alternatives --set php /usr/bin/php8.0"