<script src="/js/inc/moment.min.js"></script>
<script src="/js/inc/daterangepicker.js"></script>
<link rel="stylesheet" href="/css/inc/daterangepicker.css">
<script src="/js/inc/bootstrap4.bundle.min.js"></script>
<script src="/js/inc/bootstrap5.bundle.min.js"></script>
<script src="/js/inc/colvis/jquery.dataTables.min.js"></script>
<script src="/js/inc/jquery.dataTables.min.js"></script>
<script src="/js/inc/dataTables.fixedColumns.min.js"></script>
<script src="/js/inc/colvis/dataTables.buttons.min.js"></script>
<script src="/js/inc/dataTables.buttons.min.js"></script>
<script src="/js/inc/jszip.min.js"></script>
<script src="/js/inc/pdfmake.min.js"></script>
<script src="/js/inc/vfs_fonts.js"></script>
<script src="/js/inc/buttons.html5.min.js"></script>
<script src="/js/inc/buttons.print.min.js"></script>
<script src="/js/inc/html2pdf.bundle.min.js"></script>
<script src="/js/inc/sweetalert2.all.min.js"></script>
<script src="/js/inc/jquery-ui.min.js"></script>
<script src="/js/inc/chosen.jquery.js"></script>
<script src="/js/inc/moment.js"></script>
<script src="/js/inc/datetime.js"></script>
<script src="/js/sales/function.js?ver={{\Illuminate\Support\Str::random(50)}}"></script>
<script src="/js/inc/colvis/dataTables.responsive.min.js"></script>
<script src="/js/inc/colvis/buttons.colVis.min.js"></script>